---
pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Python 3.8 on Linux
      - check-success=Python 3.9 on Linux
      - check-success=Python 3.10 on Linux
      - check-success=Python 3.11 on Linux
      - check-success=Python 3.12 on Linux
      - check-success=Python 3.8 on Windows
      - check-success=Python 3.9 on Windows
      - check-success=Python 3.10 on Windows
      - check-success=Python 3.11 on Windows
      - check-success=Python 3.12 on Windows
      - check-success=Python 3.8 on macOS
      - check-success=Python 3.9 on macOS
      - check-success=Python 3.10 on macOS
      - check-success=Python 3.11 on macOS
      - check-success=Python 3.12 on macOS
    actions:
      merge:
        method: squash
  - name: Automatic merge for pre-commit pull requests
    conditions:
      - author=pre-commit-ci[bot]
      - check-success=pre-commit.ci - pr
    actions:
      queue:
        method: squash
